### ISSUE TITLE
Asking for paper

### ISSUE THREAD

**Issue by XXS-3** [Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction#2]
Can you provide the paper corresponding to the code

**Comment by Bosh-Kuo** [comment]
@XXS-3  I appreciate your interest in my research. The paper is currently under review, and I will promptly inform you once it is accepted and published. Thank you for your support!

**Comment by XXS-3** [comment]
Thank you so much for your reply. Looking forward to your paper.&nbsp;&nbsp;
Wish you all the best！




阳光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月18日(星期一) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction] Asking for paper (Issue #2)





 
@XXS-3  I appreciate your interest in my research. The paper is currently under review, and I will promptly inform you once it is accepted and published. Thank you for your support!

**Comment by Bosh-Kuo** [comment]
@XXS-3 
I am delighted to announce that my work has been published in *Engineering Structures*. You can access the paper through the link provided on this README page.
