### ISSUE TITLE
 ZeroDivisionError: integer modulo by zero

### ISSUE THREAD

**Issue by Norsen-Miles** [Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction#3]
While running test_GAT_LSTM.py, I encountered this weird issue. Could you provide some suggestions? Thanks!
<img width="751" alt="image" src="https://github.com/Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction/assets/154576856/cf077661-f300-40b1-ad4c-163a63d52101">

**Comment by Bosh-Kuo** [comment]
It looks like you're encountering an issue where the length of your evaluation dataset is zero.
Make sure that your evaluation dataset is being loaded correctly. Verify the path to your dataset and ensure that it is not empty or incorrectly formatted.

**Comment by Norsen-Miles** [comment]
Thanks, but the train.py runs without mistakes. I may retry it later. Btw, I saw your paper from ScienceDirect! Congratulations!







------------------ Original ------------------
From: Bosh Kuo ***@***.***&gt;
Date: Mon,Apr 22,2024 11:35 PM
To: Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction ***@***.***&gt;
Cc: Norsen-Miles ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: Re:[Bosh-Kuo/GNN-LSTM-based-Fusion-Model-for-Structural-Dynamic-Responses-Prediction] ZeroDivisionError: integer modulo by zero (Issue #3)





 
It looks like you're encountering an issue where the length of your evaluation dataset is zero.
 Make sure that your evaluation dataset is being loaded correctly. Verify the path to your dataset and ensure that it is not empty or incorrectly formatted.
